// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAc6KkJ9de1KHjn4BFOFBQh_Mj0A6AFUY',
    appId: '1:771577061234:web:411eb738e0ca4b9eb087eb',
    messagingSenderId: '771577061234',
    projectId: 'peoplefirst-791ef',
    authDomain: 'peoplefirst-791ef.firebaseapp.com',
    storageBucket: 'peoplefirst-791ef.firebasestorage.app',
    measurementId: 'G-VS3SB1D9QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpsVD5KONIIvZu-TJesalwMEUCn4AG1wM',
    appId: '1:771577061234:android:e5914cb8a66dcee0b087eb',
    messagingSenderId: '771577061234',
    projectId: 'peoplefirst-791ef',
    storageBucket: 'peoplefirst-791ef.firebasestorage.app',
  );
}
